NUM_CLASSES: &NUM_CLASSES 2
NUM_SHARDS: 1
RANDOM_SEED: 1234
SHARD_ID: 0
NUMS_GPU_USED: 1
NUMS_GPU_LOCAL: 1
ACCUM_ITER: 1
LOG_FILE_PATH: ./logs
INIT_METHOD: tcp://localhost:9999
AMP_ENABLE: False
WORLD_SIZE: 1
RANK_OFFSET: 0

DATASET:
  NUM_CLASSES: *NUM_CLASSES
  ROOT_DIR: ./Dataset
  IMG_SIZE: 128
  DATASET_NAME: CIFAR10
  TRAIN_AUGMENTATIONS:
    COMPOSE:
  TEST_AUGMENTATIONS:
    COMPOSE: [ CenterCrop ]
    CENTERCROP_PARAMS: [ 128, 128 ]

DATALOADER:
  BATCH_SIZE: 64
  PIN_MEM: True
  PREFETCH_FACTOR: 4
  NUM_WORKERS: 4


TRAIN:
  ENABLE: True
  FINETUNE: False
  MAX_EPOCH: 100
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_SAVE_PATH: Models
  CHECKPOINT_MAX_SAVE: 3
TEST:
  ENABLE: False
  TEST_CHECKPOINT_PATH:

MODEL:
  EXPORT: False
  FIND_UNUSED_PARAMETERS: False
  PRETRAINED: False
  NUM_CLASSES: *NUM_CLASSES
  FP16: False
  MODEL_NAME:


LOSS:
  LOSS_FUN: CrossEntropyLoss
  CLASS_WEIGHT: [1.0, 1.0, 1.0, 1.0]

OPTIMIZER:
  ALPHA: 0.99
  OPTIMIZER_METHOD: adam
  BASE_LR: 0.01
  ADAM_BETAS: [ 0.9, 0.999 ]
  EPS: 0.000000001
  WEIGHT_DECAY: 0.0005
  AMSGRAD: False


SCHEDULER:
  LR_NOISE_PCT: 0.67
  LR_NOISE_STD: 1.0
  SEED: 42
  LR_CYCLE_MUL: 1.0
  LR_CYCLE_DECAY: 0.95
  LR_CYCLE_LIMIT: 200
  SCHEDULER_TYPE: cosine
  MIN_LR: 0.00001
  WARMUP_LR: 0.00001
  REPEATS: 3
  WARMUP_STEPS: 0
  WARMUP_EPOCHS: 0
  CYCLE_MUL: 1
  CYCLE_DECAY: 0.95
  COOLDOWN_EPOCHS: 10
  LR_K_DECAY: 0.95
  SCHEDULER_STEP: 5
  SCHEDULER_GAMMA: 0.5
  T_IN_EPOCHS: False
